name: PR test

on:
  pull_request:
    paths-ignore:
      - README.md

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up Go
        uses: actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34 # tag=v5.3.0
        with:
          go-version-file: "go.mod"
          cache: true

      - name: install kpt
        run: |
          curl -sLO https://github.com/GoogleContainerTools/kpt/releases/download/v1.0.0-beta.38/kpt_linux_amd64-1.0.0-beta.38.tar.gz
          tar -xzf kpt_linux_amd64-1.0.0-beta.38.tar.gz
          mv kpt /usr/local/bin/

      - name: Build and test
        run: |
          make build test-bin lint container test-container
